# Generated by Django 4.2.4 on 2023-08-10 06:09

import contents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(blank=True, max_length=80, null=True)),
                ('photo', models.ImageField(max_length=150, upload_to=contents.models.user_photo_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.member')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('user_check', models.ManyToManyField(related_name='check_content', to='family.member')),
                ('user_good', models.ManyToManyField(related_name='good_content', to='family.member')),
                ('user_heart', models.ManyToManyField(related_name='heart_content', to='family.member')),
                ('user_sad', models.ManyToManyField(related_name='sad_content', to='family.member')),
                ('user_smile', models.ManyToManyField(related_name='smile_content', to='family.member')),
                ('user_worry', models.ManyToManyField(related_name='worry_content', to='family.member')),
            ],
        ),
    ]
