# Generated by Django 4.2.4 on 2023-08-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='check_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='good_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='heart_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='sad_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='smile_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='worry_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
