# Generated by Django 4.2.4 on 2023-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontent',
            name='photo',
            field=models.ImageField(upload_to='user_photos/'),
        ),
    ]
