# Generated by Django 4.2.4 on 2023-08-08 09:32

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_createcontent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontent',
            name='photo',
            field=models.ImageField(max_length=150, upload_to=contents.models.user_photo_path),
        ),
    ]
