# Generated by Django 4.2.4 on 2023-08-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0015_remove_member_member_id'),
        ('contents', '0005_alter_createcontent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontent',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='family.group'),
            preserve_default=False,
        ),
    ]
