# Generated by Django 4.2.4 on 2023-08-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('entry_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.group')),
            ],
        ),
    ]
