# Generated by Django 4.2.4 on 2023-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='profile', width_field=100),
        ),
    ]
