# Generated by Django 4.2.4 on 2023-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_thumbnail',
        ),
        migrations.AddField(
            model_name='member',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='profile_original'),
        ),
    ]
