# Generated by Django 4.2.4 on 2023-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_group_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='group',
            name='entry_number',
            field=models.CharField(max_length=4),
        ),
    ]
