# Generated by Django 4.2.4 on 2023-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_group_color_alter_group_entry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='family_code',
            field=models.TextField(default=''),
        ),
    ]
