# Generated by Django 4.2.4 on 2023-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_group_family_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='family_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
