# Generated by Django 4.2.4 on 2023-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_member_member_id_alter_group_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='family_code',
            field=models.TextField(default='', null=True),
        ),
    ]
