# Generated by Django 4.2.4 on 2023-08-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_alter_group_family_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='family_code',
        ),
    ]
