# Generated by Django 4.2.4 on 2023-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_alter_member_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
