# Generated by Django 4.2.4 on 2023-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_alter_member_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='family_name',
            field=models.CharField(max_length=10),
        ),
    ]
