# Generated by Django 4.2.4 on 2023-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0010_alter_group_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
