# Generated by Django 4.2.4 on 2023-08-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_alter_member_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='img',
            new_name='image',
        ),
    ]
