# Generated by Django 4.2.4 on 2023-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_rename_img_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.TextField(default='', null=True),
        ),
    ]
