# Generated by Django 4.2.4 on 2023-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_alter_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
    ]
